version: "3.4"

services:
  ros1-bridge:
    image: ros:galactic-ros1-bridge
    container_name: ros1_bridge
    network_mode: "host"           # access to host's network

  dev-nvidia:
    build:
        context: ../
        dockerfile: ./dingo_setup/dev.dockerfile
    image: dingo/ros:galactic
    container_name: dingo_galactic_nvidia
    network_mode: "host"           # access to host's network
    stdin_open: true               # docker run -i
    tty: true                      # docker run -t
    privileged: true               # Needed for /dev volume
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}             # Pass the display for GUI
      - QT_X11_NO_MITSHM=1             # Needed by QT programs
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
       - /tmp/.X11-unix:/tmp/.X11-unix:rw
       - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
       - ../src:/home/ros/workspace/src
       - /dev:/dev  # Needed for sensors

  dev-onboard:
    image: dingo/ros:galactic
    container_name: dingo_galactic_onboard
    network_mode: "host"           # access to host's network
    stdin_open: true               # docker run -i
    tty: true                      # docker run -t
    privileged: true               # Needed for /dev volume
    #depends_on:
    #  - ros1-bridge
    volumes:
       - ../src:/home/ros/workspace/src
       - /dev:/dev  # Needed for sensors
